"""Second high-stakes set (hs2): 144 new medical and legal/official sentences from US federal sources
(public domain), none from hs1, each with one hand-written critical error; all sealed (measured once)."""
import json, collections
SRC = {
 "cdc-food": "https://www.cdc.gov/food-safety/prevention/index.html",
 "cdc-chicken": "https://www.cdc.gov/food-safety/foods/chicken.html",
 "niddk-low": "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/low-blood-glucose-hypoglycemia",
 "fda-sun": "https://www.fda.gov/drugs/understanding-over-counter-medicines/sunscreen-how-help-protect-your-skin-sun",
 "fda-nsaid": "FDA Drug Facts label wording for NSAID pain relievers (21 CFR 201.326)",
 "cdc-heat": "https://www.cdc.gov/niosh/heat-stress/about/illnesses.html",
 "dot": "https://www.transportation.gov/individuals/aviation-consumer-protection/refunds",
 "dol": "https://www.dol.gov/agencies/whd/fmla",
 "irs": "https://www.irs.gov/businesses/small-businesses-self-employed/how-long-should-i-keep-records",
 "tsa": "https://www.tsa.gov/travel/security-screening/liquids-aerosols-gels-rule",
 "cfpb": "https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-an-error-on-my-credit-report-en-314/",
 "state": "https://travel.state.gov/en/passports/renew-replace/mail.html",
}
M, L = "medical", "legal"
ITEMS = [
# medical · number
(M,"number","cdc-chicken","Wash your hands with soap and water for at least 20 seconds before and after handling raw chicken.","Wash your hands with soap and water for at least 5 seconds before and after handling raw chicken."),
(M,"number","cdc-food","Never leave perishable food out for more than 2 hours.","Never leave perishable food out for more than 4 hours."),
(M,"number","cdc-food","If the food is exposed to temperatures above 90°F, like a hot car or picnic, refrigerate it within 1 hour.","If the food is exposed to temperatures above 90°F, like a hot car or picnic, refrigerate it within 3 hours."),
(M,"number","cdc-food","Keep your refrigerator at 40°F or below and your freezer at 0°F or below.","Keep your refrigerator at 50°F or below and your freezer at 0°F or below."),
(M,"number","cdc-food","Cook poultry to a safe minimum internal temperature of 165°F, as measured with a food thermometer.","Cook poultry to a safe minimum internal temperature of 145°F, as measured with a food thermometer."),
(M,"number","cdc-food","Allow the meat to rest for 3 minutes before carving or eating.","Allow the meat to rest for 30 minutes before carving or eating."),
(M,"number","niddk-low","If your blood glucose is less than 70 mg/dL, eat or drink 15 to 20 grams of glucose or carbohydrates right away.","If your blood glucose is less than 50 mg/dL, eat or drink 15 to 20 grams of glucose or carbohydrates right away."),
(M,"number","niddk-low","Drink half a cup, or 4 ounces, of fruit juice to treat low blood glucose.","Drink two cups, or 16 ounces, of fruit juice to treat low blood glucose."),
(M,"number","niddk-low","Increasing your physical activity can lower your blood glucose level for up to 24 hours after the activity.","Increasing your physical activity can lower your blood glucose level for up to 2 hours after the activity."),
(M,"number","fda-sun","Reapply sunscreen at least every two hours, and more often if you're sweating or swimming.","Reapply sunscreen at least every five hours, and more often if you're sweating or swimming."),
(M,"number","fda-sun","Choose a broad-spectrum sunscreen with an SPF of at least 15.","Choose a broad-spectrum sunscreen with an SPF of at least 5."),
(M,"number","fda-nsaid","The chance of severe stomach bleeding is higher if you are 60 or older.","The chance of severe stomach bleeding is higher if you are 80 or older."),
# medical · unit
(M,"unit","cdc-chicken","Wash your hands with soap and water for at least 20 seconds after handling raw chicken.","Wash your hands with soap and water for at least 20 minutes after handling raw chicken."),
(M,"unit","cdc-food","Refrigerate perishable food, such as meat, seafood, dairy and cooked leftovers, within 2 hours.","Refrigerate perishable food, such as meat, seafood, dairy and cooked leftovers, within 2 days."),
(M,"unit","cdc-food","If the food is exposed to temperatures above 90°F, refrigerate it within 1 hour.","If the food is exposed to temperatures above 90°C, refrigerate it within 1 hour."),
(M,"unit","cdc-food","Cook poultry to an internal temperature of 165°F.","Cook poultry to an internal temperature of 165°C."),
(M,"unit","cdc-food","Let the meat rest for 3 minutes before carving or eating it.","Let the meat rest for 3 hours before carving or eating it."),
(M,"unit","niddk-low","If your blood glucose is below your target, take 15 to 20 grams of glucose or carbohydrates right away.","If your blood glucose is below your target, take 15 to 20 milligrams of glucose or carbohydrates right away."),
(M,"unit","niddk-low","Drink 4 ounces of fruit juice to treat low blood glucose.","Drink 4 quarts of fruit juice to treat low blood glucose."),
(M,"unit","niddk-low","Physical activity can lower your blood glucose for up to 24 hours afterward.","Physical activity can lower your blood glucose for up to 24 days afterward."),
(M,"unit","fda-sun","Reapply sunscreen every two hours when you are outdoors.","Reapply sunscreen every two days when you are outdoors."),
(M,"unit","fda-sun","Apply sunscreen 15 minutes before sun exposure.","Apply sunscreen 15 hours before sun exposure."),
(M,"unit","fda-sun","An average-sized adult needs at least one ounce of sunscreen to cover the body from head to toe.","An average-sized adult needs at least one pound of sunscreen to cover the body from head to toe."),
(M,"unit","fda-nsaid","Stop use and ask a doctor if pain gets worse or lasts more than 10 days.","Stop use and ask a doctor if pain gets worse or lasts more than 10 weeks."),
# medical · negation
(M,"negation","cdc-food","Never thaw food on the counter.","Thaw food on the counter."),
(M,"negation","cdc-food","Raw chicken is ready to cook and doesn't need to be washed first.","Raw chicken is ready to cook but needs to be washed first."),
(M,"negation","niddk-low","If you have kidney disease, don't drink orange juice, because it has a lot of potassium.","If you have kidney disease, drink orange juice, because it has a lot of potassium."),
(M,"negation","fda-sun","Sunscreen is not recommended for infants under six months old.","Sunscreen is recommended for infants under six months old."),
(M,"negation","fda-sun","Spray sunscreens should never be applied directly to your face.","Spray sunscreens should be applied directly to your face."),
(M,"negation","fda-nsaid","Do not use if you have ever had an allergic reaction to any other pain reliever or fever reducer.","Use it even if you have had an allergic reaction to another pain reliever or fever reducer."),
(M,"negation","cdc-heat","Stay with the worker until emergency medical services arrive.","Do not stay with the worker until emergency medical services arrive."),
(M,"negation","cdc-food","Never leave perishable food out for more than 2 hours.","You can leave perishable food out for more than 2 hours."),
(M,"negation","cdc-food","It is okay to put small portions of hot food in the refrigerator, since they will chill faster.","It is not okay to put small portions of hot food in the refrigerator, even though they will chill faster."),
(M,"negation","cdc-food","If a food is recalled, throw it away.","If a food is recalled, don't throw it away."),
(M,"negation","cdc-heat","Call 911 for emergency medical care.","Do not call 911 for emergency medical care."),
(M,"negation","niddk-low","You might eat a snack before physical activity to prevent low blood glucose.","You should not eat a snack before physical activity, to prevent low blood glucose."),
# medical · direction
(M,"direction","cdc-chicken","Wash your hands for 20 seconds after handling raw chicken.","Wash your hands for 20 seconds before handling raw chicken, but not after."),
(M,"direction","cdc-food","Keep your refrigerator at 40°F or below.","Keep your refrigerator at 40°F or above."),
(M,"direction","fda-nsaid","The chance of stomach bleeding is higher if you are 60 or older.","The chance of stomach bleeding is higher if you are 60 or younger."),
(M,"direction","fda-sun","Apply sunscreen 15 minutes before sun exposure.","Apply sunscreen 15 minutes after sun exposure."),
(M,"direction","fda-sun","Sunscreen is not recommended for infants under six months old.","Sunscreen is not recommended for infants over six months old."),
(M,"direction","fda-sun","Choose a broad-spectrum sunscreen with an SPF of at least 15.","Choose a broad-spectrum sunscreen with an SPF of at most 15."),
(M,"direction","niddk-low","If your blood glucose is below your target, take 15 to 20 grams of glucose right away.","If your blood glucose is above your target, take 15 to 20 grams of glucose right away."),
(M,"direction","niddk-low","Physical activity can lower your blood glucose during the activity and for hours afterward.","Physical activity can raise your blood glucose during the activity and for hours afterward."),
(M,"direction","fda-nsaid","The risk of heart attack or stroke is higher if you use more than directed or for longer than directed.","The risk of heart attack or stroke is higher if you use less than directed or for shorter than directed."),
(M,"direction","fda-sun","Limit time in the sun between 10 a.m. and 2 p.m., when the sun's rays are most intense.","Limit time in the sun between 10 a.m. and 2 p.m., when the sun's rays are least intense."),
(M,"direction","cdc-heat","Move the worker to a shaded, cool area.","Move the worker to a sunny, warm area."),
(M,"direction","fda-sun","Reapply sunscreen at least every two hours, and more often if you're sweating or swimming.","Reapply sunscreen at least every two hours, and less often if you're sweating or swimming."),
# medical · condition
(M,"condition","cdc-food","Raw meat, poultry, seafood, and eggs can spread germs to ready-to-eat food unless you keep them separate.","Raw meat, poultry, seafood, and eggs can spread germs to ready-to-eat food even if you keep them separate."),
(M,"condition","niddk-low","If you have kidney disease, don't drink orange juice.","Unless you have kidney disease, don't drink orange juice."),
(M,"condition","niddk-low","If you drink alcoholic beverages, it's safer to eat some food at the same time.","Unless you drink alcoholic beverages, it's safer to eat some food at the same time."),
(M,"condition","cdc-food","If the food is exposed to temperatures above 90°F, refrigerate it within 1 hour.","Unless the food is exposed to temperatures above 90°F, refrigerate it within 1 hour."),
(M,"condition","fda-nsaid","Ask a doctor before use if you are taking a diuretic.","Ask a doctor before use unless you are taking a diuretic."),
(M,"condition","fda-nsaid","Stop use and ask a doctor if pain gets worse or lasts more than 10 days.","Stop use and ask a doctor if pain gets worse and lasts more than 10 days."),
(M,"condition","fda-nsaid","The risk is higher if you use more than directed or for longer than directed.","The risk is higher only if you use more than directed and for longer than directed."),
(M,"condition","cdc-food","If a food is recalled, throw it away.","Unless a food is recalled, throw it away."),
(M,"condition","fda-sun","Reapply sunscreen every two hours, and more often if you're sweating or swimming.","Reapply sunscreen every two hours, and more often unless you're sweating or swimming."),
(M,"condition","fda-nsaid","Do not use this product if you have ever had an allergic reaction to a pain reliever.","Do not use this product unless you have had an allergic reaction to a pain reliever."),
(M,"condition","niddk-low","If your blood glucose is below your target, eat or drink 15 to 20 grams of carbohydrates right away.","Unless your blood glucose is below your target, eat or drink 15 to 20 grams of carbohydrates right away."),
(M,"condition","cdc-food","Never leave perishable food out for more than 2 hours, or 1 hour if it is exposed to temperatures above 90°F.","Never leave perishable food out for more than 2 hours, or 1 hour unless it is exposed to temperatures above 90°F."),
# medical · role (who / what)
(M,"role","cdc-heat","Stay with the worker until emergency medical services arrive.","The worker should stay with you until emergency medical services arrive."),
(M,"role","niddk-low","Ask your health care team if any of your diabetes medicines can cause low blood glucose.","Your health care team will ask you if any of their medicines can cause low blood glucose."),
(M,"role","fda-sun","Ask a doctor before applying sunscreen to children under six months of age.","A doctor should ask you before applying sunscreen to children under six months of age."),
(M,"role","fda-sun","FDA recommends that infants be kept out of the sun between 10 a.m. and 2 p.m.","FDA recommends that older adults be kept out of the sun between 10 a.m. and 2 p.m."),
(M,"role","cdc-heat","Move the worker to a shaded, cool area.","The worker should move you to a shaded, cool area."),
(M,"role","niddk-low","You may need to check your blood glucose before, during, and after physical activity.","Your coach may need to check their blood glucose before, during, and after physical activity."),
(M,"role","niddk-low","If you have kidney disease, don't drink orange juice.","If your child has kidney disease, don't let them drink orange juice."),
(M,"role","niddk-low","Ask your health care team how you can prevent and treat symptoms of low blood glucose.","Your health care team will ask you how they can prevent and treat symptoms of low blood glucose."),
(M,"role","fda-nsaid","Do not use if you have ever had an allergic reaction to any other pain reliever.","Do not use if your parent has ever had an allergic reaction to any other pain reliever."),
(M,"role","cdc-chicken","Wash your hands with soap and water before and after handling raw chicken.","Wash the chicken with soap and water before and after handling it."),
(M,"role","cdc-food","Raw chicken is ready to cook and doesn't need to be washed first.","Raw chicken is ready to eat and doesn't need to be cooked first."),
(M,"role","fda-sun","Spray sunscreens should never be applied directly to your face.","Spray sunscreens should never be applied directly to your hands."),
# legal · number
(L,"number","dot","A refund is due within 7 business days after you reject an offer if you paid for the ticket with a credit card.","A refund is due within 17 business days after you reject an offer if you paid for the ticket with a credit card."),
(L,"number","dot","A refund is due within 20 calendar days if you paid with another form of payment, such as a check or cash.","A refund is due within 60 calendar days if you paid with another form of payment, such as a check or cash."),
(L,"number","dot","A flight is significantly delayed if you arrive 3 hours or more later than scheduled on a domestic itinerary.","A flight is significantly delayed if you arrive 5 hours or more later than scheduled on a domestic itinerary."),
(L,"number","dot","For international itineraries, a significant delay means arriving 6 hours or more late.","For international itineraries, a significant delay means arriving 12 hours or more late."),
(L,"number","dot","Passengers are entitled to a refund of their checked bag fee if it is not delivered within 12 hours of their domestic flight arriving at the gate.","Passengers are entitled to a refund of their checked bag fee if it is not delivered within 24 hours of their domestic flight arriving at the gate."),
(L,"number","dol","Eligible employees may take up to 12 workweeks of leave in a 12-month period.","Eligible employees may take up to 16 workweeks of leave in a 12-month period."),
(L,"number","dol","Employees must have at least 1,250 hours of service with the employer during the 12 months before their leave starts.","Employees must have at least 2,250 hours of service with the employer during the 12 months before their leave starts."),
(L,"number","dol","The employee must work at a location where the employer has at least 50 employees within 75 miles.","The employee must work at a location where the employer has at least 15 employees within 75 miles."),
(L,"number","irs","Keep records for 3 years if none of the special situations apply to you.","Keep records for 2 years if none of the special situations apply to you."),
(L,"number","tsa","Liquids in carry-on bags are limited to containers of 3.4 ounces or less per item.","Liquids in carry-on bags are limited to containers of 6.8 ounces or less per item."),
(L,"number","cfpb","Furnishers generally must investigate and respond to your dispute within 30 days of when they receive it.","Furnishers generally must investigate and respond to your dispute within 90 days of when they receive it."),
(L,"number","state","You can renew your passport by mail if it was issued within the last 15 years.","You can renew your passport by mail if it was issued within the last 25 years."),
# legal · unit
(L,"unit","dot","A refund is due within 7 business days if you paid with a credit card.","A refund is due within 7 business weeks if you paid with a credit card."),
(L,"unit","dot","A refund is due within 20 calendar days if you paid by check or cash.","A refund is due within 20 calendar months if you paid by check or cash."),
(L,"unit","dot","A domestic flight is significantly changed if it arrives 3 hours or more later than scheduled.","A domestic flight is significantly changed if it arrives 3 days or more later than scheduled."),
(L,"unit","dot","You can get your bag fee back if your checked bag is not delivered within 12 hours of a domestic flight.","You can get your bag fee back if your checked bag is not delivered within 12 days of a domestic flight."),
(L,"unit","dol","Eligible employees may take up to 12 workweeks of leave in a 12-month period.","Eligible employees may take up to 12 months of leave in a 12-month period."),
(L,"unit","dol","A family member of a covered servicemember may take up to 26 workweeks of leave in a single 12-month period.","A family member of a covered servicemember may take up to 26 days of leave in a single 12-month period."),
(L,"unit","irs","Keep records for 7 years if you file a claim for a loss from worthless securities.","Keep records for 7 months if you file a claim for a loss from worthless securities."),
(L,"unit","irs","Keep employment tax records for at least 4 years after the tax becomes due or is paid.","Keep employment tax records for at least 4 months after the tax becomes due or is paid."),
(L,"unit","tsa","Each liquid item in your carry-on must be 100 milliliters or less.","Each liquid item in your carry-on must be 100 liters or less."),
(L,"unit","tsa","The purchase must have been made within 48 hours.","The purchase must have been made within 48 days."),
(L,"unit","cfpb","Furnishers must respond to your dispute within 30 days of receiving it.","Furnishers must respond to your dispute within 30 weeks of receiving it."),
(L,"unit","state","Passports for applicants 16 and older are valid for 10 years.","Passports for applicants 16 and older are valid for 10 months."),
# legal · negation
(L,"negation","dot","If you chose to take a significantly delayed flight, you are not entitled to a refund under DOT rules.","If you chose to take a significantly delayed flight, you are entitled to a refund under DOT rules."),
(L,"negation","dol","An eligible employee may not take intermittent leave for the birth of a child unless the employer agrees.","An eligible employee may take intermittent leave for the birth of a child unless the employer agrees."),
(L,"negation","dol","Employers are required to provide FMLA leave where all requirements are met.","Employers are not required to provide FMLA leave where all requirements are met."),
(L,"negation","irs","Keep records indefinitely if you do not file a return.","Keep records indefinitely if you file a return."),
(L,"negation","irs","When your records are no longer needed for tax purposes, do not discard them until you check whether you have to keep them longer.","When your records are no longer needed for tax purposes, you can discard them without checking whether you have to keep them longer."),
(L,"negation","tsa","Pack items in containers larger than 3.4 ounces in checked baggage.","Do not pack items in containers larger than 3.4 ounces in checked baggage."),
(L,"negation","tsa","The items inside the secure bags must be screened and cleared.","The items inside the secure bags do not need to be screened and cleared."),
(L,"negation","cfpb","Then, the credit reporting companies must update your credit reports.","Then, the credit reporting companies do not have to update your credit reports."),
(L,"negation","dot","You are entitled to a refund if the airline cancelled your flight and you choose not to travel.","You are entitled to a refund if the airline cancelled your flight and you choose to travel."),
(L,"negation","dot","Airlines must let you know that you are entitled to a refund if you don't accept the offer.","Airlines must let you know that you are entitled to a refund if you accept the offer."),
(L,"negation","state","You can renew by mail if your passport was issued when you were 16 or older.","You cannot renew by mail if your passport was issued when you were 16 or older."),
(L,"negation","dol","To request leave, employees must communicate with their employer about their leave needs.","To request leave, employees do not need to communicate with their employer about their leave needs."),
# legal · direction
(L,"direction","dot","A refund is due within 7 business days after you reject the airline's offer.","A refund is due at least 7 business days after you reject the airline's offer."),
(L,"direction","dot","A flight is significantly changed if you arrive 3 hours or more later than scheduled.","A flight is significantly changed if you arrive 3 hours or more earlier than scheduled."),
(L,"direction","dol","Employees must have at least 1,250 hours of service during the 12 months before their leave starts.","Employees must have at least 1,250 hours of service during the 12 months after their leave starts."),
(L,"direction","dol","The employer must have at least 50 employees within 75 miles.","The employer must have at most 50 employees within 75 miles."),
(L,"direction","irs","Keep employment tax records for at least 4 years after the tax becomes due or is paid, whichever is later.","Keep employment tax records for at least 4 years after the tax becomes due or is paid, whichever is earlier."),
(L,"direction","irs","Returns filed before the due date are treated as filed on the due date.","Returns filed after the due date are treated as filed on the due date."),
(L,"direction","tsa","Liquids are limited to travel-sized containers of 3.4 ounces or less per item.","Liquids are limited to travel-sized containers of 3.4 ounces or more per item."),
(L,"direction","tsa","Pack items in containers larger than 3.4 ounces in checked baggage.","Pack items in containers smaller than 3.4 ounces in checked baggage."),
(L,"direction","state","You can renew by mail if your passport was issued when you were 16 or older.","You can renew by mail if your passport was issued when you were 16 or younger."),
(L,"direction","state","Passports for applicants 16 and older are valid for 10 years.","Passports for applicants under 16 are valid for 10 years."),
(L,"direction","state","You can renew by mail if your passport was issued within the last 15 years.","You can renew by mail if your passport was issued more than 15 years ago."),
(L,"direction","tsa","The receipt must show the purchase was made within the last 48 hours.","The receipt must show the purchase was made more than 48 hours ago."),
# legal · condition
(L,"condition","dot","You are entitled to a refund if the airline cancelled your flight and you choose not to travel.","You are entitled to a refund if the airline cancelled your flight or you choose not to travel."),
(L,"condition","dot","If you chose to take a significantly delayed flight, you are not entitled to a refund.","Unless you chose to take a significantly delayed flight, you are not entitled to a refund."),
(L,"condition","dot","If the downgraded passenger continues to travel, the airline must refund the difference between the original fare and the lower fare.","Unless the downgraded passenger continues to travel, the airline must refund the difference between the original fare and the lower fare."),
(L,"condition","dot","Passengers can get their bag fee refunded if the bag is not delivered within 12 hours.","Passengers can get their bag fee refunded unless the bag is not delivered within 12 hours."),
(L,"condition","dol","To be eligible, employees must have at least 1,250 hours of service and work at a location with at least 50 employees within 75 miles.","To be eligible, employees must have at least 1,250 hours of service or work at a location with at least 50 employees within 75 miles."),
(L,"condition","dol","An employee may not take intermittent leave for the birth of a child unless the employer agrees.","An employee may not take intermittent leave for the birth of a child if the employer agrees."),
(L,"condition","irs","Keep records for 7 years if you file a claim for a loss from worthless securities.","Keep records for 7 years unless you file a claim for a loss from worthless securities."),
(L,"condition","irs","Keep records indefinitely if you do not file a return.","Keep records indefinitely unless you do not file a return."),
(L,"condition","cfpb","If the information cannot be verified, the furnisher must update or remove it.","Unless the information cannot be verified, the furnisher must update or remove it."),
(L,"condition","dot","Airlines must tell you that you are entitled to a refund if you don't accept their offer.","Airlines must tell you that you are entitled to a refund unless you don't accept their offer."),
(L,"condition","irs","Keep employment tax records for 4 years after the date the tax becomes due or is paid, whichever is later.","Keep employment tax records for 4 years after the date the tax becomes due and is paid."),
(L,"condition","dot","A refund is due within 20 calendar days if you paid with another form of payment, such as a check or cash.","A refund is due within 20 calendar days unless you paid with another form of payment, such as a check or cash."),
# legal · role
(L,"role","dot","Airlines must issue refunds within seven business days for credit card purchases.","Passengers must pay the airline back within seven business days for credit card purchases."),
(L,"role","dot","Airlines must let you know that you are entitled to a refund.","You must let the airline know that it is entitled to a refund."),
(L,"role","dol","Employees must communicate with their employer about their leave needs.","Employers must communicate with their employees about their own leave needs."),
(L,"role","dol","Employers are required to provide FMLA leave where all requirements are met.","Employees are required to provide FMLA leave where all requirements are met."),
(L,"role","dol","A family member of a covered servicemember may take up to 26 workweeks of leave to care for the servicemember.","A covered servicemember may take up to 26 workweeks of leave to care for a family member."),
(L,"role","cfpb","Furnishers must investigate and respond to your dispute within 30 days.","You must investigate and respond to the furnisher's dispute within 30 days."),
(L,"role","cfpb","The furnisher must update or remove the information and notify all the credit reporting companies.","The credit reporting companies must update or remove the information and notify the furnisher."),
(L,"role","cfpb","The credit reporting companies must update your credit reports.","You must update the credit reporting companies' records."),
(L,"role","tsa","The items inside the secure bags must be screened and cleared by TSA.","The items inside the secure bags must be screened and cleared by the passenger."),
(L,"role","dot","If the downgraded passenger continues to travel, the airline must refund the fare difference to the passenger.","If the downgraded passenger continues to travel, the passenger must pay the fare difference to the airline."),
(L,"role","irs","You must keep records for 3 years.","The IRS keeps your records for 3 years."),
(L,"role","state","You can renew your passport by mail if it was issued when you were 16 or older.","Your parent must renew your passport by mail if it was issued when you were 16 or older."),
]
assert len(ITEMS) == 144, len(ITEMS)
c = collections.Counter((d, k) for d, k, *_ in ITEMS); assert set(c.values()) == {12}, c
items = []
for i, (dom, kind, src, en, bad) in enumerate(ITEMS):
    assert en != bad, en
    items.append({"id": 9201 + i, "domain": dom, "kind": kind, "source": SRC[src], "en": en, "bad_en": bad, "split": "test"})
langs = ["vie_Latn", "jpn_Jpan", "kor_Hang", "zho_Hans", "spa_Latn", "arb_Arab", "hin_Deva", "fra_Latn", "tgl_Latn", "por_Latn", "urd_Arab"]
json.dump({"langs": langs, "items": items}, open("items-hs2.json", "w"), ensure_ascii=False, indent=1)
print(len(items), "items, all sealed")
